workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 10
    instance_type: mac_mini_m2
    environment:
      groups:
        - yandex
    scripts:
      - name: Build Flutter Web
        script: |
          flutter create . --platforms=web
          flutter build web --release --dart-define=YANDEX_API_KEY=$YANDEX_API_KEY --dart-define=YANDEX_FOLDER_ID=b1gu1l2c8thgnac4nusp
    artifacts:
      - build/web/**/*
